// videogameActionTypes.js
export const FETCH_VIDEOGAMES_START = 'FETCH_VIDEOGAMES_START';
export const FETCH_VIDEOGAMES_SUCCESS = 'FETCH_VIDEOGAMES_SUCCESS';
export const FETCH_VIDEOGAMES_ERROR = 'FETCH_VIDEOGAMES_ERROR';
